name: Deploy Swing Trading App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Node.js dependencies
      run: npm install
    
    - name: Build frontend
      run: npm run build
    
    - name: Test application
      run: |
        timeout 60s streamlit run app.py --server.headless true --server.port 8501 &
        sleep 30
        curl -f http://localhost:8501 || exit 1

  deploy-streamlit:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to Streamlit Cloud
      run: |
        echo "Deployment to Streamlit Cloud is automatic when pushing to main branch"
        echo "Make sure your repository is connected to Streamlit Cloud"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref_name }}"